language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev
  - git submodule update --init --recursive
cache: apt
script:
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - make
